config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'charges/reset_payment', to: 'charges#reset_payment', as: :reset_payment
  get 'parents/:id/pay_tuition', to: "parents#pay_tuition", as: :pay_tuition
  get 'users/welcome_teacher', to: "users#welcome_teacher", as: :welcome_teacher
  get '/health' => 'welcome#health', as: :health
  resources :rooms, except: [:destroy, :update]
  get "/.well-know/acme-challenge/#{ENV['LE_AUTH_REQUEST']}", to: 'welcome#letsencrypt'
  get "/parents/:id/my_children", to: 'parents#my_children', as: :my_children
  get "/parents/:parent_id/children/:id/my_child_info", to: 'parents#my_child_info', as: :my_child_info
  get "/auth/:provider/callback", to: "sessions#create"
  get 'users/:id/attendees' => "users#attendees", as: :attendees
  get 'users/:id/my_class' => "users#my_class", as: :my_class
  delete "/logout" => "sessions#destroy", as: :logout
  get '/infos/new_forms' => "infos#new_forms", as: :new_forms
  post '/children/email' => "children#send_emails", as: :send_emails
  post '/children/:id/attend' => "children#attend", as: :attend
  get '/children/:id/my_child' => "children#my_child", as: :my_child
  get '/children/:id/edit_my_child' => "children#edit_my_child", as: :edit_my_child
  post '/children/sms' => "children#send_text_message", as: :send_text_message
  resources :sessions, except: [:update, :destroy]
  resources :infos, except: [:destroy]
  resources :parents, except: [:destroy] do
    resources :children do
      resource :charges
    end
  end

  post '/users' => 'users#welcome', as: :welcome
  resources :users do
    resources :children do
      resources :infos
    end
  end
  resources :children

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  # def create
  #   @child = Child.create(child_params)
  #   if @child.save
  #     redirect_to @child, notice: 'Child was successfully created.'
  #    else
  #      render action: 'new'
  #   end
  # end

  def edit
    @child = Child.find(params[:id])
  end

  def edit_my_child
    @child = Child.find(params[:id])
    @parent = Parent.find(params[:parent_id])
  end


  def attend
    @child = Child.find(params[:id])
    if @child.attend
      @child.attend = false
    else
      @child.attend = true
    end

    @child.save
    render json: [], status: 200
  end

  def update
    @child = Child.find(params[:id])
    @parent = Parent.find(params[:parent_id]) if !params[:parent_id].nil?
    @child.update(child_params)
    if @child.save
      if !@parent.nil?
        redirect_to my_children_path(@parent)
      else
        redirect_to user_child_path(@current_user.id, @child.id)
      end
    else
      render :edit
    end
  end

  # def new
  #   @child = Child.new
  # end

  def index
    @user = @current_user
    @children = @user.children
  end

  def show
    @child = Child.find(params[:id])
    @parent = @child.parent
  end

  def my_child
    @child = Child.find(params[:id])
    @parent = Parent.find(params[:parent_id])
  end

  def send_emails
    user = @current_user
    @children = user.children
    @children.each do |child|
      SendInfo.send_info(child.email, child).deliver_now
    end
    # child = user.children.last
    # SendInfo.send_info(child.email, child).deliver_now
    redirect_to my_class_path(user.id)
  end

  def send_text_message
    # message = "(Check) Your Child is not in school"
    twilio_sid = ENV["TWILIO_ACCOUNT_SID"]
    twilio_token = ENV["TWILIO_AUTH_TOKEN"]
    twilio_phone_number = ENV["TWILIO_PHONE_NUMBER"]

    children = @current_user.children
    children.each do |child|
      if !child.attend
        @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
        @twilio_client.account.messages.create(
          :from => twilio_phone_number,
          :to => child.parent1_number,
          :body => "Good Morning " + child.parents_names + ", " + child.name + " is not in school"
        )

      end
    end
    redirect_to my_class_path(@current_user.id)
  end


  private

  def child_params
    params.require(:child).permit(:avatar, :name, :last_name, :parents_names, :gender)
  end

end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.erb
<%= form_for(@child, multipart: true) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :room_id %>
    <%= f.text_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit 'Make a child' %>
    <%= link_to 'Nevermind', children_path, class: 'button' %>
  </div>
<% end %>

app/views/children/_form.html.erb
<%= form_for(@child, multipart: true) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <%= hidden_field_tag(:parent_id, @parent.id) %>
    <%= f.submit 'Save the info' %>
    <!-- <%= link_to 'Nevermind', children_path, class: 'button' %> -->
  </div>
<% end %>

app/views/children/edit.html.erb
<h1> Edit child information </h1>
<%= render "form" %>

app/views/children/edit_my_child.html.erb
<%= form_for(@child, multipart: true) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <%= hidden_field_tag(:parent_id, @parent.id) %>
    <%= f.submit 'Save the info' %>
    <!-- <%= link_to 'Nevermind', children_path, class: 'button' %> -->
  </div>
<% end %>

app/views/children/index.html.erb
<h1> Hey <%= @user.name %> </h1>
<h2><%= @user.room.name %> Class </h2>
<br>
<% @children.each do |child| %>
  <big><%= link_to child.name, child_path(child.id) %></big>
  <% info = child.infos.last %>
  <% if info.diaper_m %>
    <p> morning diaper:  <%= info.diaper_m %> </p>
  <% end %>
  <% if info.more_daiper %>
    <p> <%= child.name %> needs more diapers </p>
  <% end %>
  <% if info.more_wipes %>
    <p> <%= child.name %> needs more wipes </p>
  <% end %>
  <% if info.more_clothes %>
    <p> <%= child.name %> needs more clothes </p>
  <% end %>
  <br>
  <%= link_to "Edit info", edit_user_child_info_path(@user.id, child.id, info.id) %>
  <br>
  <br>
  <br>
  <br>
<% end %>
<%= link_to "See class", room_path(@user.room) %>
<%= button_to "Send SMS", send_text_message_path, params: { user_id: @user.id } %>
<%= button_to "Send emails to parents" ,send_emails_path, params: { user_id: @user.id }  %>

app/views/children/my_child.html.erb
<h1 class="middle-name"> <%= @child.name %> </h1>
<br>
<br>
<br>
<br>

<div class="row">
  <div class="col-md-6">
    <!-- <h3> <%= link_to "Add Photo", edit_child_path(@child.id) %> </h3> -->
    <div class="image-right">
      <%= image_tag @child.avatar.url(:square) %>
    </div>
  </div>
  <div class="col-md-6">
    <h2 style="font-family: 'Josefin Sans', serif;">Parents names: <stuff><%= @child.parents_names %></stuff></h2>
    <h2 style="font-family: 'Josefin Sans', serif;">Address: <stuff><%= @parent.address%></stuff></h2>
    <h2 style="font-family: 'Josefin Sans', serif;">Phone number 1: <stuff><%= @parent.phone_number1 %></stuff></h2>
    <% if !@parent.phone_number2.nil? %>
      <h2 style="font-family: 'Josefin Sans', serif;">Phone number 2: <stuff><%= @parent.phone_number2 %></stuff></h2>
    <% end %>
    <h2 style="font-family: 'Josefin Sans', serif;">Email: <stuff><%= @parent.email %></stuff></h2>
    <br>
    <%= button_to "Edit Info", edit_parent_path(@parent.id), params: {:child_id => @child.id}, :method => :get, class:"btn btn-info left-side" %>
  </div>
</div>
<%= link_to "Add Photo", edit_my_child_path(@child.id, :parent_id => @parent.id) %>

app/views/children/new.html.erb
<h1> Add new child </h1>
<%= render "form" %>

app/views/children/show.html.erb
<h1 class="middle-name"><%= @child.name %> </h1>
<br>
<br>
<br>
<br>

<div class="row">
  <div class="col-md-6">
    <!-- <h3> <%= link_to "Add Photo", edit_child_path(@child.id) %> </h3> -->
    <div class="image-right">
      <%= image_tag @child.avatar.url(:square) %>
    </div>
  </div>
  <div class="col-md-6">
    <h2 style="font-family: 'Josefin Sans', serif;">Parents names: <stuff><%= @child.parents_names %></stuff></h2>
    <h2 style="font-family: 'Josefin Sans', serif;">Phone number 1: <stuff><%= @parent.phone_number1 %></stuff></h2>
    <% if !@parent.phone_number2.nil? %>
      <h2 style="font-family: 'Josefin Sans', serif;">Phone number 2: <stuff><%= @parent.phone_number2 %></stuff></h2>
    <% end %>
    <h2 style="font-family: 'Josefin Sans', serif;">Email: <stuff><%= @parent.email %></stuff></h2>
  </div>
</div>

<%= link_to "Add Photo", edit_child_path(@child.id) %>