config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'charges/reset_payment', to: 'charges#reset_payment', as: :reset_payment
  get 'parents/:id/pay_tuition', to: "parents#pay_tuition", as: :pay_tuition
  get 'users/welcome_teacher', to: "users#welcome_teacher", as: :welcome_teacher
  get '/health' => 'welcome#health', as: :health
  resources :rooms, except: [:destroy, :update]
  get "/.well-know/acme-challenge/#{ENV['LE_AUTH_REQUEST']}", to: 'welcome#letsencrypt'
  get "/parents/:id/my_children", to: 'parents#my_children', as: :my_children
  get "/parents/:parent_id/children/:id/my_child_info", to: 'parents#my_child_info', as: :my_child_info
  get "/auth/:provider/callback", to: "sessions#create"
  get 'users/:id/attendees' => "users#attendees", as: :attendees
  get 'users/:id/my_class' => "users#my_class", as: :my_class
  delete "/logout" => "sessions#destroy", as: :logout
  get '/infos/new_forms' => "infos#new_forms", as: :new_forms
  post '/children/email' => "children#send_emails", as: :send_emails
  post '/children/:id/attend' => "children#attend", as: :attend
  get '/children/:id/my_child' => "children#my_child", as: :my_child
  get '/children/:id/edit_my_child' => "children#edit_my_child", as: :edit_my_child
  post '/children/sms' => "children#send_text_message", as: :send_text_message
  resources :sessions, except: [:update, :destroy]
  resources :infos, except: [:destroy]
  resources :parents, except: [:destroy] do
    resources :children do
      resource :charges
    end
  end

  post '/users' => 'users#welcome', as: :welcome
  resources :users do
    resources :children do
      resources :infos
    end
  end
  resources :children

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :children, through: :room
  validates :email, :name, :provider, presence: true
  belongs_to :room

  def self.find_or_create_from_omniauth(auth_hash, &block)
   user = self.find_by(email: auth_hash['info']['email'])
  # user.url = auth_hash['info']['urls'][user.provider.capitalize]
   if !user.nil?
     # User found continue on with your life
     return user
   else
     # Create a new user
     user = User.new
     user.email        = auth_hash['info']['email']
     user.provider   = auth_hash['provider']
     user.name   = auth_hash["info"]["name"]
  #   user.last_name      = auth_hash["info"]["last_name"]
    yield user if block_given?
     if user.save
       return user
     else
       return nil
     end
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def my_class
    info = @current_user.children.last.infos.last
    if info.created_at.strftime('%D')!= DateTime.now.strftime('%D')
      redirect_to :new_forms
    else
      @user = @current_user
      @children = @user.children
    end

  end

  def welcome_teacher
    @user = @current_user
  end

  def attendees
    @user = @current_user
    @children = @user.children
  end

  def index
    @users = User.all
  end

  # def welcome
  #   email = "misshershi@gmail.com"
  #   WelcomeMailer.welcome(email, @current_user).deliver_now
  #   redirect_to :back
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/attendees.html.erb
<div class="header-att"> Attendance </div>

<div class="row">
  <% @children.each do |child| %>
    <div class="col-md-4">
        <div class= "child-name child-details"><%= link_to child.name, child_path(child.id) %></div>
        <br>
        <% if child.attend %>
          <%= image_tag child.avatar.url(:square) , :class => "child-image attend" %>
        <% else %>
          <%= image_tag child.avatar.url(:square) , :class => "child-image not-attend" %>
        <% end %>
        <br>
        <br>
      </div>
  <% end %>
</div>
<br>
<br>
<%= button_to "Send SMS", send_text_message_path, params: { user_id: @user.id } %>

app/views/users/index.html.erb
<h1>List of all teachers</h1>

<% @users.each do |teacher| %>
  <%= link_to teacher.name, user_path(teacher.id) %><br>
<% end %>

app/views/users/my_class.html.erb
<h2 class="header-att"><%= @user.room.name %> Class </h2>
<div class="row">
  <% @children.each do |child| %>
    <div class="col-md-4">
      <div class= "child-name child-details"><%= link_to child.name, child_path(child.id) %></div>
      <% info = child.infos.last %>
      <br>
      <% info = child.infos.last %>
      <%= link_to image_tag(child.avatar.url(:square), :class => "child-border"), edit_user_child_info_path(@current_user.id, child.id, info.id) %>
      <br>
      <br>
    </div>
  <% end %>
</div>
<br>
<%= button_to "Send emails to parents" ,send_emails_path, params: { user_id: @user.id }  %>

app/views/users/show.html.erb
<h1> Hey <%= @user.name %> </h1>
<h2>Rainbow Class (Room's name)</h2>

<% @children.each do |child| %>
  <%= link_to child.name, child_path(child.id) %>
<% end %>

app/views/users/welcome_teacher.html.erb
<div class="image">

  <!-- <h1 class="header-red"><%= link_to "Welcome " + @current_user.name, root_path %></h1>
  <p> -->
    <!-- <%= image_tag "299895_orig.jpg", :class => "image-welcome2" %> -->
    <%= image_tag "Daycare_Clip-Art-1.jpg" , :class=> "image-welcome"%>
<br>
<br>
<br>
    <!-- this button do 2 things: 1. It will create new forms for all kids. 2. it will
    make all children be "not attend" -->
</div>