config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'charges/reset_payment', to: 'charges#reset_payment', as: :reset_payment
  get 'parents/:id/pay_tuition', to: "parents#pay_tuition", as: :pay_tuition
  get 'users/welcome_teacher', to: "users#welcome_teacher", as: :welcome_teacher
  get '/health' => 'welcome#health', as: :health
  resources :rooms, except: [:destroy, :update]
  get "/.well-know/acme-challenge/#{ENV['LE_AUTH_REQUEST']}", to: 'welcome#letsencrypt'
  get "/parents/:id/my_children", to: 'parents#my_children', as: :my_children
  get "/parents/:parent_id/children/:id/my_child_info", to: 'parents#my_child_info', as: :my_child_info
  get "/auth/:provider/callback", to: "sessions#create"
  get 'users/:id/attendees' => "users#attendees", as: :attendees
  get 'users/:id/my_class' => "users#my_class", as: :my_class
  delete "/logout" => "sessions#destroy", as: :logout
  get '/infos/new_forms' => "infos#new_forms", as: :new_forms
  post '/children/email' => "children#send_emails", as: :send_emails
  post '/children/:id/attend' => "children#attend", as: :attend
  get '/children/:id/my_child' => "children#my_child", as: :my_child
  get '/children/:id/edit_my_child' => "children#edit_my_child", as: :edit_my_child
  post '/children/sms' => "children#send_text_message", as: :send_text_message
  resources :sessions, except: [:update, :destroy]
  resources :infos, except: [:destroy]
  resources :parents, except: [:destroy] do
    resources :children do
      resource :charges
    end
  end

  post '/users' => 'users#welcome', as: :welcome
  resources :users do
    resources :children do
      resources :infos
    end
  end
  resources :children

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children


  def more_then_one?
    if self.children.count > 1
      return true
    else
      return false
    end
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

  def index
    @user = @current_user
    @parent = Parent.find_by(email: @user.email)
    # @parent = Parent.create(name: "new parent") if @parent.nil?
    # find the parent
  end

  def my_children
    @parent = Parent.find(params[:id])
    @children = @parent.children
  end

  def my_child_info
    @parent = Parent.find(params[:parent_id])
    @child = Child.find(params[:id])
    @infos = @child.infos
  end

  def edit
    @parent = Parent.find(params[:id])
    @child = Child.find(params[:child_id])

  end

  def update
    @parent = Parent.find(params[:id])
    @child = Child.find(params[:parent][:child_id])
    if @parent.update(parent_params)
      redirect_to my_child_path(@child.id, parent_id: @parent.id )
    else
      render :edit
    end
  end

  def pay_tuition
    @parent = Parent.find(params[:id])
    @children = @parent.children
    month = DateTime.now.strftime('%m')
    @months = {"01" => "January", "02" => "February", "03" => "March", "04" => "April", "05" => "May"}
    @current_month = @months[month]
    @current_year = DateTime.now.strftime('%Y')
  end

  private

    def parent_params
      params.require(:parent).permit(:name, :email, :phone_number1, :last_name, :address)
    end


end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/edit.html.erb
  <%= form_for @parent do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
          <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :address %><br>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number1, class: 'form-control' %>
      </div>
      <%= f.hidden_field :child_id, :value => @child.id %>
      <br>
      <div class="actions bottom-margin text-center">
        <%= f.submit 'Save', class: "btn btn-primary", params: {child_id: @child.id} %>
      </div>
  <% end %>
</form>

app/views/parents/index.html.erb
<%= image_tag "Daycare_Clip-Art-1.jpg" , :class=> "image-welcome"%>

app/views/parents/my_child_info.html.erb
<br>
<h1 style="font-family: 'Josefin Sans', serif;"> <%= link_to @child.name, my_child_path(@child.id, :parent_id => @parent.id)%> <small>Daily Information History</h1></small>

<br>
<br>
<% @infos.each do |info| %>
  <h2 style="font-family: 'Josefin Sans', serif;"> <stuff-big><%= info.created_at.strftime('%D') %></stuff-big></h2>
<div class="border">
  <div class="row">
    <div class="col-md-3">
      <h3 class="info_h3">Diapers</h3>
      <table class="table table-stripe">
        <thead>
          <th>Morning </th>
          <th>Noon </th>
          <th>Afternoon </th>
        </thead>
        <tbody>
          <tr class="success">
            <td><%= info.diaper_m %></td>
            <td><%= info.diaper_n %></td>
            <td><%= info.diaper_a %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <h3 class="info_h3">Meals</h3>
      <table class="table table-stripe">
        <thead>
          <th> Morning </th>
          <th> Noon </th>
          <th> Afternoon</th>
        </thead>
        <tbody>
          <tr class="warning">
            <td><%= info.breakfast %></td>
            <td><%= info.lunch %></td>
            <td><%= info.afternoon %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <h3 class="info_h3">General Info</h3>
      <br>
      <table class="table table-stripe">
        <thead>
          <th></th>
        </thead>
        <tbody>
          <tr class="info">
            <td><%= info.general %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <h3 class="info_h3">Sleep time</h3>
      <br>
      <table class="table table-stripe">
        <thead>
          <th></th>
        </thead>
        <tbody>
          <tr class="active">
            <td><%= info.sleep_time %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <% if info.more_daiper || info.more_wipes || info.more_clothes %>
    <h3 class="info_h3">More Of</h3>
    <% if info.more_clothes %>
      <p>✔️ Clothes</p>
    <% end %>
    <% if info.more_daiper %>
      <p>✔️ Daipers</p>
    <% end %>
    <% if info.more_wipes %>
      <p>✔️ Wipes</p>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/parents/my_children.html.erb
<h2 class="header-att"> <%= @parent.name %>'s Children </h2>
<div class="row">
  <% @children.each do |child| %>
    <div class="col-md-4">
      <div class= "child-name child-details"><%= link_to child.name, my_child_path(child.id ,:parent_id => @parent.id) %></div>
      <% info = child.infos.last %>
      <br>
      <% info = child.infos.last %>
      <%= link_to image_tag(child.avatar.url(:square), :class => "child-border"), my_child_info_path(@parent.id, child.id) %>
      <br>
      <br>
    </div>
  <% end %>
</div>
<br>

app/views/parents/pay_tuition.html.erb
<h1 style="font-family: 'Josefin Sans', serif;"> Payment for <stuff-big> <%= @current_month +" " + @current_year%></stuff-big> </h1>
<br>
<table class="table table-hover">
  <thead>
    <th> Child Name </th>
    <th> Class </th>
    <th> Monthly Tution </th>
    <th> Discount </th>
    <th> Final Charge</th>
    <th>  </th>
  </thead>
  <% if !@parent.more_then_one? %>
    <% @child = @children.last %>
      <% @amount = @child.room.tuition %>
      <tbody>
        <tr>
          <td><%= @child.name %></td>
          <td><%= @child.room.name %></td>
          <td>$ <%= @amount/100 %></td>
          <td> none </td>
          <td><%= @amount/100 %></td>
          <% if !@child.paid? %>
            <td> <%= render "charges/form", :parent => @parent, :child => @child, :amount => @amount %></td>
          <% else %>
            <td> Paid</td>
          <% end %>
        </tr>
      </tbody>
  <% else %>
    <% t_child = Child.highest_tuition(@children) %>
    <% high_tuistion = t_child.room.tuition %>
    <tbody>
      <tr>
        <% @children.each do |child| %>
          <% if child == t_child %>
            <!-- <h2 style="font-family: 'Indie Flower', serif;"><%= child.name %>:</h2> -->
              <% @child = t_child %>
              <% @amount = high_tuistion %>
              <% @discount = false %>
          <% else %>
          <!-- <h2 style="font-family: 'Indie Flower', serif;"><%= child.name %>:</h2> -->
            <% @amount = child.room.tuition * 90/100 %>
            <% @child = child %>
            <% @discount = true %>
          <% end %>
          <td><%= @child.name %></td>
          <td><%= @child.room.name %></td>
          <td>$ <%= @child.room.tuition/100 %></td>
          <% if @discount %>
            <td> 10% </td>
          <% else %>
            <td> none </td>
          <% end %>
          <td  style="font-size:20px;">$<%= @amount/100 %></td>
          <% if !@child.paid? %>
            <td> <%= render "charges/form", :parent => @parent, :child => @children.last, :amount => @children.last.room.tuition %></td>
          <% else %>
            <td>Paid</td>
          <% end %>
      </tr>
    <% end %>
  <% end %>

<%= button_to "reset payment", reset_payment_path %>

app/views/parents/payment_history.html.erb
<% children.each do |child| %>