config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'charges/reset_payment', to: 'charges#reset_payment', as: :reset_payment
  get 'parents/:id/pay_tuition', to: "parents#pay_tuition", as: :pay_tuition
  get 'users/welcome_teacher', to: "users#welcome_teacher", as: :welcome_teacher
  get '/health' => 'welcome#health', as: :health
  resources :rooms, except: [:destroy, :update]
  get "/.well-know/acme-challenge/#{ENV['LE_AUTH_REQUEST']}", to: 'welcome#letsencrypt'
  get "/parents/:id/my_children", to: 'parents#my_children', as: :my_children
  get "/parents/:parent_id/children/:id/my_child_info", to: 'parents#my_child_info', as: :my_child_info
  get "/auth/:provider/callback", to: "sessions#create"
  get 'users/:id/attendees' => "users#attendees", as: :attendees
  get 'users/:id/my_class' => "users#my_class", as: :my_class
  delete "/logout" => "sessions#destroy", as: :logout
  get '/infos/new_forms' => "infos#new_forms", as: :new_forms
  post '/children/email' => "children#send_emails", as: :send_emails
  post '/children/:id/attend' => "children#attend", as: :attend
  get '/children/:id/my_child' => "children#my_child", as: :my_child
  get '/children/:id/edit_my_child' => "children#edit_my_child", as: :edit_my_child
  post '/children/sms' => "children#send_text_message", as: :send_text_message
  resources :sessions, except: [:update, :destroy]
  resources :infos, except: [:destroy]
  resources :parents, except: [:destroy] do
    resources :children do
      resource :charges
    end
  end

  post '/users' => 'users#welcome', as: :welcome
  resources :users do
    resources :children do
      resources :infos
    end
  end
  resources :children

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :parent
  helper_method :positive_adjectives
  before_action :require_login
  before_action :current_user

  def positive_adjectives
    words = ["Creative", "Funny", "Kind", "Nice", "Loving", "Sweet", "Adorable"]
    return words[rand(words.length-1)]
  end

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
   rescue ActiveRecord::RecordNotFound
  end

  def parent
    if !@current_user.nil?
      if @current_user.user_type == "p"
        @parent = Parent.find_by(email: @current_user.email)
      end
    end
  end

  def require_login
    unless current_user
      flash[:error] = "Please log in"
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<!-- <footer>
  <nav>
    <ul>
      <p id="foot">Webpage by <%= link_to "Tammy Hershi", "https://github.com/TamarHershi" %> &copy; <%= Time.now.year %></p>
      <li>Copyright &copy; <%= Time.now.year %> All rights reserved.</li>
    </ul>
  </nav>
</footer> -->

<!-- <footer>
  <div id="footer">
  Webpage by <%= link_to "Tammy Hershenbaum", "https://github.com/TamarHershi" %>  <br>
  Copyright &copy; <%= Time.now.year %> All rights reserved.
  </div>
</footer> -->

app/views/application/_navbar.html.erb
<% if @current_user %>
<div id="navigation_container">
  <div class="l-triangle-top"></div>
  <div class="l-triangle-bottom"></div>
  <div class="rectangle">
    <% if @current_user.user_type == "t" %>
      <ul id="navigation">
        <li><%= link_to @current_user.name, root_path %></li>
        <li><%= link_to "My class", my_class_path(@current_user.id) %></li>
        <li><%= link_to "Attendance", attendees_path(@current_user.id) %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
    <% elsif @current_user.user_type == "p" %>
      <ul id="navigation">
        <li><%= link_to @parent.name, parents_path %></li>
        <li><%= link_to "My children", my_children_path(@parent.id) %></li>
        <li><%= link_to "Pay Tuition", pay_tuition_path(@parent.id) %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
    <% end %>
  </div>

  <div class="r-triangle-top"></div>
  <div class="r-triangle-bottom"></div>
</div>

<% end %>